######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 11 15:34:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BaseWindow.h
SOURCES += BaseWindow.cpp main.cpp
