######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 18 11:13:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH +=
INCLUDEPATH +=

# Input
HEADERS += BaseWindow.h
SOURCES += BaseWindow.cpp \
           main.cpp \
